"""Task 32: STATUS.md must be renderable from RESULTS.json, never invented."""
import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
import render_status  # noqa: E402


class RenderStatusTest(unittest.TestCase):
    def test_missing_results_json_is_a_noop(self):
        with tempfile.TemporaryDirectory() as td:
            self.assertEqual(render_status.main([td]), 0)
            self.assertFalse((Path(td) / "STATUS.md").exists())

    def test_render_rows_come_from_results_only(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            (root / "RESULTS.json").write_text(json.dumps({
                "tasks": [{"id": "27", "status": "SHIPPED",
                           "name": "observability", "commit": "abc123"}]},
            ), encoding="utf-8")
            self.assertEqual(render_status.main([str(root)]), 0)
            text = (root / "STATUS.md").read_text(encoding="utf-8")
            self.assertIn("| 27 | SHIPPED | observability | `abc123` |", text)
            self.assertIn("Generated by", text)

    def test_render_function_is_pure(self):
        text = render_status.render({"tasks": []}, "deadbeef")
        self.assertIn("`deadbeef`", text)
        self.assertIn("| ID | Status | Focus | Evidence |", text)


if __name__ == "__main__":
    unittest.main()
