#!/usr/bin/env python3
"""Render STATUS.md from the canonical RESULTS.json to eliminate doc drift.

Task 32. Hand-edited status tables drift from verified results; this script
regenerates the ledger section of STATUS.md from RESULTS.json, the single
machine-readable source of truth for task/defect states. When RESULTS.json is
absent the script reports and exits 0, so it is safe to wire into CI on
branches that have not produced a results file yet. It never invents a row:
every line comes from the JSON, and the git SHA is stamped from the live
repository so a stale render is visibly stale.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NL = chr(10)


def _git_sha(root: Path) -> str:
    try:
        out = subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"],
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip() if out.returncode == 0 else "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def render(results: dict, git_sha: str) -> str:
    lines = [
        "# JitTest Canonical Status",
        "",
        "- **Current Git SHA**: `" + git_sha + "`",
        "- **Generated by**: `scripts/render_status.py` (do not hand-edit)",
        "",
        "## Task & Verification Ledger",
        "| ID | Status | Focus | Evidence |",
        "|---|---|---|---|",
    ]
    for item in results.get("tasks", []):
        lines.append(
            "| {} | {} | {} | `{}` |".format(
                item.get("id", ""), item.get("status", ""),
                item.get("name", ""), item.get("commit", "")))
    lines.append("")
    lines.append("Nothing in this file claims a result that RESULTS.json does not record.")
    return NL.join(lines) + NL


def main(argv: list[str] | None = None) -> int:
    argv = list(argv if argv is not None else sys.argv[1:])
    root = Path(argv[0]) if argv else ROOT
    results_path = root / "RESULTS.json"
    status_path = root / "STATUS.md"
    if not results_path.exists():
        print("RESULTS.json not found; skipping render")
        return 0
    with open(results_path, encoding="utf-8") as fh:
        data = json.load(fh)
    text = render(data, _git_sha(root))
    status_path.write_text(text, encoding="utf-8")
    print("Rendered " + status_path.name + " from " + results_path.name + " ("
          + str(len(data.get("tasks", []))) + " row(s)).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
